export const StarNameConst: string[] = [
    'Solskinn',
    'Mionzi HA7',
    'Majakas AE9',
    'Ollmhor',
    'Aurinko RF2',
    'Giggadon LP8',
    'Alazar',
    'Jiplamar',
    'Valaistus',
    'Galmazar PK2',
    'Sliabh WP6',
    'Radialis',
    'Rippundor VK9',
    'Xamar RS8',
    'Xadrorix',
    'Corzor YF0',
    'Bato ZG5',
    'Jiplamar',
    'Krushka',
    'Mionzi',
    'Hindamar XM1',
    'Giggadon',
    'Onkodis HJ5',
    'Massiivinen',
    'Cawr',
    'Solskinn',
    'Enzanmar YH6',
    'Brilo RQ3',
    'Cyrulas',
    'Valgustus'
];