export enum TerritoryType {
    PLANET_GREEN = 'PLANET_GREEN',
    PLANET_SAND = 'PLANET_SAND',
    PLANET_RINGED = 'PLANET_RINGED',
    PLANET_METAL = 'PLANET_METAL',
    STAR_SOLAR = 'STAR_SOLAR'
}
