export enum BuildingObjectType {
    // Units
    SCOUT_SHIP = 'SCOUT_SHIP',
    COLONIAL_SHIP = 'COLONIAL_SHIP',
    ANALYSIS_SHIP = 'ANALYSIS_SHIP',

    // Common
    WATER_FILTER = 'WATER_FILTER',
    SUNLIGHT_AMPLIFIER = 'SUNLIGHT_AMPLIFIER'
}
