export enum TourEffectPriorityEnum {
    UNIT_INIT_MOVE_TOUR_EFFECT_PRIORITY = 998,
    UNIT_ROTATE_TOUR_EFFECT_PRIORITY = 999,
    UNIT_MOVE_TOUR_EFFECT_PRIORITY = 1000,

    START_BUILDING_PROCESS = 5000,
    AFTER_BUILDING_PROCESS = 5001,
    CLEAR_FINISHED_BUILDINGS = 5002,

    REFILL_GAME_OBJECTS = 9999
}
